language: php
php:
  - 8.0
cache:
  directories:
    "vendor"
env:
  global:
    - XDEBUG_MODE=coverage
before_script:
  - composer install
  - vendor/bin/phinx migrate -e testing
script: vendor/bin/phpunit --testdox
after_success:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/php-coveralls -v
