language: php
php:
  - 8.0
cache:
  directories:
    "vendor"

before_script:
  - composer install
  - vendor/bin/phinx migrate -e testing
script: ./vendor/bin/phpunit --testdox
after_success:
  - ./vendor/bin/phpunit --log-junit build/logs/clover.xml
  - vendor/bin/php-coveralls -v