version: 2

jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: cimg/php:8.0

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout

      - run: sudo add-apt-repository ppa:ondrej/php
      - run: sudo apt update
      - run: sudo apt list --upgradable
      - run: sudo apt install php8.0-xdebug
      - run: php -d xdebug.mode=coverage
      - run: php -v
      - run: php -i

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - composer-v1-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - composer-v1-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
        
      # Database
      - run: vendor/bin/phinx migrate -e testing

      # Test
      - run: vendor/bin/phpunit --testdox
      - run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml
      - run: vendor/bin/php-coveralls -v
      - store_artifacts:
          path: build/logs
          destination: clover.xml
